default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DATABASE_HOST') { 'postgres' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  timeout: 5000

development:
  <<: *default
  database: appress_development

test:
  <<: *default
  database: appress_test

production:
  url: <%= ENV['DATABASE_URL'] %>
